[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.0.0"
  NEXT_TELEMETRY_DISABLED = "1"

# Build caching for faster rebuilds
[build.cache]
  paths = [
    ".next/cache",
    "node_modules/.cache",
    ".bun/cache"
  ]

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/brand/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Expires headers for image files - JPG/JPEG
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for image files - PNG
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for image files - WebP
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for image files - AVIF
[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for image files - GIF
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for image files - SVG
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for image files - ICO (favicons)
[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for images in subdirectories
[[headers]]
  for = "/*/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for images in deeper subdirectories (uploads, assets, etc.)
[[headers]]
  for = "/*/*/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# ===== CSS FILES =====
# Expires headers for CSS files - Root directory
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for CSS files - Subdirectories
[[headers]]
  for = "/*/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for CSS files - Deeper subdirectories
[[headers]]
  for = "/*/*/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# ===== JAVASCRIPT FILES =====
# Expires headers for JavaScript files - Root directory
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for JavaScript files - Subdirectories
[[headers]]
  for = "/*/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for JavaScript files - Deeper subdirectories
[[headers]]
  for = "/*/*/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# ===== FONT FILES =====
# Expires headers for WOFF fonts
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for WOFF2 fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for TTF fonts
[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for EOT fonts
[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# Expires headers for OTF fonts
[[headers]]
  for = "/*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Mon, 01 Jan 2025 00:00:00 GMT"

# ===== SOURCE MAP FILES =====
# Expires headers for source map files (shorter cache for debugging)
[[headers]]
  for = "/*.map"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Expires = "Sun, 15 Sep 2024 00:00:00 GMT"

[[headers]]
  for = "/*/*.map"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Expires = "Sun, 15 Sep 2024 00:00:00 GMT"

[[headers]]
  for = "/*/*/*.map"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Expires = "Sun, 15 Sep 2024 00:00:00 GMT"

# ===== MANIFEST AND CONFIG FILES =====
# Expires headers for JSON files (medium cache duration)
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Expires = "Sat, 21 Sep 2024 00:00:00 GMT"

[[headers]]
  for = "/*/*.json"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Expires = "Sat, 21 Sep 2024 00:00:00 GMT"

# Expires headers for XML files (sitemaps, feeds)
[[headers]]
  for = "/*.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Expires = "Sun, 15 Sep 2024 01:00:00 GMT"

# ===== SERVICE WORKER FILES =====
# Service worker files - no cache to ensure updates
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires = "0"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Expires = "0"

# ===== ROBOTS AND SITEMAP =====
# Robots.txt - short cache for SEO updates
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Expires = "Sun, 15 Sep 2024 01:00:00 GMT"

# Sitemap files - medium cache
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Expires = "Sun, 15 Sep 2024 01:00:00 GMT"
